{% set name = "PyTrilinos" %}
{% set version = "12.12.1" %}

package:
  name: {{ name | lower }}
  version: {{ version }}

source:
  url: http://github.com/trilinos/Trilinos/archive/trilinos-release-{{ version | replace('.', '-') }}.tar.gz
  sha256: 5474c5329c6309224a7e1726cf6f0d855025b2042959e4e2be2748bd6bb49e18

build:
  number: 0
  skip: True  # [ win ]

requirements:
  build:
    - cmake 3.9.6
    - {{ compiler('fortran') }}
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - mpi
    - python
    - swig 3.0.11
    - doxygen
    - numpy
    - mpi4py
    - trilinos {{ version }}

  run:
    - mpi
    - mpi4py
    - python
    - {{ pin_compatible('numpy') }}

test:
  requires:
    - cmake 3.9.6
    - mpi4py
  imports:
    - PyTrilinos.Teuchos
    - PyTrilinos.Epetra
    - PyTrilinos.TriUtils
    - PyTrilinos.Tpetra
    - PyTrilinos.EpetraExt
    - PyTrilinos.Domi
    - PyTrilinos.AztecOO
    - PyTrilinos.Galeri
    - PyTrilinos.Amesos
    - PyTrilinos.IFPACK
    - PyTrilinos.Komplex
    - PyTrilinos.ML
    - PyTrilinos.Anasazi

about:
  home: https://trilinos.github.io
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  summary:
    Python interfaces to Sandia's suite of HPC solvers and enabling technologies
  description:
    Python interfaces to fast, compiled object-oriented algorithms and
    enabling technologies that support the solution of large-scale, complex
    multi-physics engineering and scientific problems.
  dev_url: https://github.com/trilinos/Trilinos

extra:
  recipe-maintainers:
    - pyt-viper
