travis:
  secure:
    BINSTAR_TOKEN: VrGs9V41Wa1exdud5L+Wt0BcHvKr7gNf44q2QrbI7RA0KFcyh/OP0j+3pTzSx4n/6EuM/D1dqzsRu6WiZ1kcFwaNRWSgLymYmdF3rjaQSf59bDSQURVJGaoFN9x4C6dsHzqrfPXNwoNDFsL+up/MMs2Os9iNo4rBzf9ElQPA7Di7q7hllj6YSiXkjSUQYiIG6jo+OjmUH8fso0kQDpRQYMSM6rvsMaLAFWuXeoExazA2YzIIEKfNoiDFghwyqUWuXrSh14XBm3mwRd+nzYvZuhJvxrYofiQKvXhlNNE3MArZQSwCDOEk770UBMBBMtU8/em5pk8JUKEvviBV9aqotYspuEdC+PVefz8wOR0LPGLT/vgIQ1R81aMijrz8Hrw/qvwurRSnUj5FYNNwHPVyBEoLwfIx5nM03dDNRGEKJGCA2rFW9oPbXkbucQKl2IePlgoIR3OOYmFTEjO7SyZ2uNLWKRk4S7/9Pq5phyWN597wIx+ZDiTdEShJQaFRVJjVMpQEhQ8ra300bAU4Y8TT5JCL2dTgoPZGhGgyFAoHDwxHVfsIX8jD2pQlMdp3fe5Jk3vdHdvUyr+tFZGQtzm3CzGkpfbcOHEUb8U6BdGpPnfyHMYom7kIwcBLzA/RcG+Q397OsrHN8PQYF/02vW34OlpFnqwV/ISuPyED6P26mJk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
