travis:
  secure:
    BINSTAR_TOKEN: hRL50buMnMX5nGSNVQG+gDIfIfVqkbSKYO9Tx/qoSFsk8QE5fZ/Q+sB2WH+zWrYo2ybrko5RShVMiHqSmde8K9OjAqcTcItJV81mQ2+2/7uPv5FnjDqzM+qvgRKRmVBEHtHrePfaqN+4zdXNTWghAvkRpYzJ6E5P7k719NpqNqLnYnfIZrF7c7+cUjjrfH9i/FCMop/h/a4Xos9hC6TalE/iFU2Q5SMh3/evhn7XQgh2DRwqzHq3DxDKU7G9XgI4ZpZOIbEQMojjzgK3Ke8dlqWJMaCtiutV0ZhNujSFjT8Wk+cn0yea1rgsa7ySmQTqMwLqZyMPSr8RvzMNgobbxtNL1V/kmVY3bKw+8KKWtrL7F9Svh6sqgIY8ve477srsKApwM7SUz4+MWY/Cf0h9p/CNTzlA7tfN1ZH+6leYUeVOoSbAlJXd8fr6v17c20O3JAWbfy9ipS63sWkvKBQ8yO+3NodGAiQJz9knUXZfW7FPT0eyIko/1gGbKcgYA0LUz7btOMLNr9HBMKRwoMqBc1lGBKck8YUvZV9HVVQbPq0DRvRJNj8pj1lJhiNc3nXCQVqswZna+c5WjNCpLOSz6oQhFUfMeWit6qEYcElBmFpsajlTz5pSqM5Qo90YK+qNgIQN2AukAX4zrR2d6IydP9J+IFcQ1s6oePGhbf4phDU=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
